#!/bin/bash
app-to-icon() {
  wmctrl -l | grep "$1" | awk '{print $1}' | {
    while IFS= read -r id_hex; do
      xseticon -id $((id_hex)) "$2"
    done
  }
}

app-to-icon "Obsidian" "/usr/share/pixmaps/obsidian.png"
